# Generated by Django 4.2.21 on 2026-08-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_clientrequirement_approval_status_and_more'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='crm.crmclient'),
        ),
    ]
