# Generated by Django 4.2.21 on 2026-08-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAttendanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('clock-in', 'Clock in'), ('clock-out', 'Clock out')], max_length=16)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('biometric_verified', models.BooleanField(default=False)),
                ('selfie', models.ImageField(upload_to='mobile_attendance/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
