# Generated by Django 4.2.21 on 2026-08-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_update_company_name_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepage',
            name='is_published',
        ),
        migrations.AddField(
            model_name='websitepage',
            name='aeo',
            field=models.BooleanField(default=False, help_text='Automated Expert Optimization flag'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='aiseo_score',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='AI‑generated SEO score', max_length=10),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='eeat_rating',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='EEAT rating', max_length=10),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='geo',
            field=models.CharField(blank=True, help_text='Geographic targeting information', max_length=100),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='llmo',
            field=models.CharField(blank=True, help_text='Local Language Meta Optimization', max_length=100),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
