# Generated by Django 4.2.21 on 2026-08-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_faq_portfolioproject_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='website/media/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(default='#ff7a00', max_length=20)),
                ('secondary_color', models.CharField(default='#111b35', max_length=20)),
                ('font_family', models.CharField(default='Poppins, sans-serif', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-is_active', 'name'),
            },
        ),
        migrations.AddField(
            model_name='websitepage',
            name='page_order',
            field=models.PositiveIntegerField(default=0, help_text='Used for sorting pages globally if needed'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Override the page title for SEO purposes', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesection',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced configuration for margins, padding, styles, etc.'),
        ),
        migrations.AddField(
            model_name='websitesection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged In Only'), ('admin_only', 'Admin Only')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=10),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('url', models.CharField(blank=True, help_text='Direct URL or path.', max_length=500)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.navigationmenu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='website.websitepage')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.navigationitem')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
