# Generated by Django 4.2.21 on 2026-08-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_mediaasset_navigationmenu_themesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='is_dynamic_render',
            field=models.BooleanField(default=False, help_text='If true, uses the new Component-based Dynamic CMS rendering.'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='html_content',
            field=models.TextField(blank=True, help_text='Complete editable HTML for this page (Legacy Mode).'),
        ),
    ]
