# Generated by Django 4.2.21 on 2026-08-27 18:21

from django.db import migrations, models
import django.db.models.deletion


def migrate_legacy_section_items(apps, schema_editor):
    Section = apps.get_model('website', 'WebsiteSection')
    SectionItem = apps.get_model('website', 'WebsiteSectionItem')
    for section in Section.objects.all().iterator():
        items = section.items if isinstance(section.items, list) else []
        for order, item in enumerate(items):
            if not isinstance(item, dict):
                continue
            title = str(item.get('title') or item.get('heading') or item.get('name') or '').strip()
            if not title:
                continue
            SectionItem.objects.create(
                section_id=section.pk,
                title=title[:180],
                subtitle=str(item.get('subtitle') or '')[:180],
                description=str(item.get('description') or item.get('content') or ''),
                value=str(item.get('value') or '')[:80],
                icon=str(item.get('icon') or '')[:100],
                button_text=str(item.get('button_text') or '')[:80],
                button_url=str(item.get('button_url') or item.get('url') or '')[:500],
                sort_order=order,
            )
        if section.section_type == 'hero' and items:
            buttons = [item for item in items if isinstance(item, dict) and item.get('title') and item.get('url')]
            updates = {}
            if buttons:
                updates.update(primary_button_text=str(buttons[0]['title'])[:80], primary_button_url=str(buttons[0]['url'])[:500])
            if len(buttons) > 1:
                updates.update(secondary_button_text=str(buttons[1]['title'])[:80], secondary_button_url=str(buttons[1]['url'])[:500])
            if updates:
                Section.objects.filter(pk=section.pk).update(**updates)


def preserve_legacy_data(apps, schema_editor):
    # Legacy JSON and HTML fields intentionally remain in place; rollback only
    # removes their structured copies.
    apps.get_model('website', 'WebsiteSectionItem').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_websitepage_is_dynamic_render_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitesection',
            name='primary_button_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='websitesection',
            name='primary_button_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='websitesection',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='websitesection',
            name='secondary_button_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='html_content',
            field=models.TextField(blank=True, editable=False, help_text='Preserved legacy content. New pages use structured sections.'),
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='items',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Preserved legacy items; use structured section items.'),
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text', 'Text / introduction'), ('image', 'Image and text'), ('services', 'Services grid'), ('features', 'Feature grid'), ('stats', 'Statistics'), ('testimonials', 'Testimonials'), ('team', 'Team members'), ('faq', 'FAQ'), ('contact', 'Contact'), ('cta', 'Call to action')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='settings',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Preserved legacy settings.'),
        ),
        migrations.CreateModel(
            name='WebsiteSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, help_text='Useful for statistics, e.g. 250+.', max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='website/section-items/')),
                ('icon', models.CharField(blank=True, help_text='Optional Font Awesome class.', max_length=100)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='website.websitesection')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.RunPython(migrate_legacy_section_items, preserve_legacy_data),
    ]
