# Generated by Django 4.2.21 on 2026-08-27 18:23

from django.db import migrations, models


def enable_structured_pages(apps, schema_editor):
    Page = apps.get_model('website', 'WebsitePage')
    Section = apps.get_model('website', 'WebsiteSection')
    defaults = {
        'services': ('services', 'Technology services built for growth', 'Explore solutions managed from the CMS.'),
        'pricing': ('pricing', 'Simple, transparent plans', 'Choose a plan that fits your business.'),
        'career': ('jobs', 'Build meaningful technology with us', 'Explore current opportunities.'),
        'contact': ('contact', 'Let’s start a conversation', 'Tell us what you want to build or improve.'),
        'faq': ('faq', 'Frequently asked questions', 'Helpful answers from our team.'),
        'team': ('team', 'Meet our team', 'The people behind our work.'),
        'projects': ('projects', 'Selected work', 'A look at solutions delivered by our team.'),
    }
    for slug in ('home', 'about'):
        Page.objects.filter(slug=slug, sections__isnull=False).update(is_dynamic_render=True)
    for slug, (section_type, heading, subheading) in defaults.items():
        page = Page.objects.filter(slug=slug).first()
        if not page:
            continue
        if not page.sections.exists():
            Section.objects.create(page=page, section_type=section_type, heading=heading, subheading=subheading)
        page.is_dynamic_render = True
        page.save(update_fields=['is_dynamic_render'])


def disable_seeded_pages(apps, schema_editor):
    Page = apps.get_model('website', 'WebsitePage')
    Page.objects.filter(slug__in=['home', 'about', 'services', 'pricing', 'career', 'contact', 'faq', 'team', 'projects']).update(is_dynamic_render=False)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_navigationitem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text', 'Text / introduction'), ('image', 'Image and text'), ('services', 'Services grid'), ('features', 'Feature grid'), ('stats', 'Statistics'), ('pricing', 'Pricing plans'), ('jobs', 'Job openings'), ('projects', 'Portfolio projects'), ('testimonials', 'Testimonials'), ('team', 'Team members'), ('faq', 'FAQ'), ('contact', 'Contact'), ('cta', 'Call to action')], default='text', max_length=50),
        ),
        migrations.RunPython(enable_structured_pages, disable_seeded_pages),
    ]
