# Generated by Django 4.2.21 on 2026-08-27 18:25

from django.db import migrations


def normalize_types(apps, schema_editor):
    Section = apps.get_model('website', 'WebsiteSection')
    mapping = {
        'content': 'text',
        'about': 'image',
        'who_we_are': 'features',
        'what_we_do': 'services',
        'get_started': 'cta',
    }
    for old_type, new_type in mapping.items():
        Section.objects.filter(section_type=old_type).update(section_type=new_type)


def keep_normalized_types(apps, schema_editor):
    # The old aliases were ambiguous; rollback keeps the safe structured types.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_websitesection_section_type'),
    ]

    operations = [migrations.RunPython(normalize_types, keep_normalized_types)]
