# Generated by Django 4.2.21 on 2026-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_normalize_legacy_section_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='website/carousel/')),
                ('primary_button_text', models.CharField(blank=True, max_length=80)),
                ('primary_button_url', models.CharField(blank=True, max_length=500)),
                ('secondary_button_text', models.CharField(blank=True, max_length=80)),
                ('secondary_button_url', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WebsiteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('solution', 'Solution')], default='solution', max_length=20)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='website/products/')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('button_text', models.CharField(default='Learn more', max_length=80)),
                ('button_url', models.CharField(default='/contact/', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='additional_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated supporting keywords.'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical override.'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='social_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='social_image',
            field=models.ImageField(blank=True, upload_to='website/social/'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='social_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websiteservice',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='header_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='header_cta_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='map_directions_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Map embed URL; do not enter an API key here.'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='office_hours',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text', 'Text / introduction'), ('image', 'Image and text'), ('services', 'Services grid'), ('features', 'Feature grid'), ('stats', 'Statistics'), ('pricing', 'Pricing plans'), ('jobs', 'Job openings'), ('projects', 'Portfolio projects'), ('carousel', 'Carousel'), ('products', 'Products / solutions'), ('testimonials', 'Testimonials'), ('team', 'Team members'), ('faq', 'FAQ'), ('contact', 'Contact'), ('cta', 'Call to action')], default='text', max_length=50),
        ),
    ]
