# Generated by Django 4.2.21 on 2026-08-28 03:10

from django.db import migrations, models


def consolidate_duplicate_settings(apps, schema_editor):
    Settings = apps.get_model('website', 'WebsiteSettings')
    Map = apps.get_model('website', 'ContactMapConfig')
    NavigationMenu = apps.get_model('website', 'NavigationMenu')
    NavigationItem = apps.get_model('website', 'NavigationItem')
    HeaderMenu = apps.get_model('website', 'HeaderMenu')

    map_config = Map.objects.first()
    settings = Settings.objects.first()
    if map_config and settings:
        updates = {}
        if map_config.embed_url and not settings.map_embed_url:
            updates['map_embed_url'] = map_config.embed_url
        if map_config.address and not settings.address:
            updates['address'] = map_config.address
        if map_config.phone and not settings.phone:
            updates['phone'] = map_config.phone
        if map_config.email and not settings.email:
            updates['email'] = map_config.email
        if updates:
            Settings.objects.filter(pk=settings.pk).update(**updates)

    main, _ = NavigationMenu.objects.get_or_create(slug='main', defaults={'name': 'Main navigation', 'is_active': True})
    if not main.items.exists():
        source = HeaderMenu.objects.filter(is_active=True).first()
        if source:
            parent_map = {}
            for item in source.items.order_by('sort_order', 'id'):
                copied = NavigationItem.objects.create(
                    menu=main, label=item.label, url=item.url, page_id=item.page_id,
                    parent_id=parent_map.get(item.parent_id), open_in_new_tab=item.open_in_new_tab,
                    sort_order=item.sort_order, is_active=item.is_active,
                )
                parent_map[item.pk] = copied.pk


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_seed_seo_metadata'),
    ]

    operations = [
        migrations.RunPython(consolidate_duplicate_settings, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ContactMapConfig',
        ),
        migrations.RemoveField(
            model_name='headermenuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='headermenuitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='headermenuitem',
            name='parent',
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text', 'Text / introduction'), ('image', 'Image and text'), ('services', 'Services grid'), ('features', 'Feature grid'), ('stats', 'Statistics'), ('pricing', 'Pricing plans'), ('jobs', 'Job openings'), ('projects', 'Portfolio projects'), ('tech', 'Technology / expertise'), ('carousel', 'Carousel'), ('products', 'Products / solutions'), ('testimonials', 'Testimonials'), ('team', 'Team members'), ('faq', 'FAQ'), ('contact', 'Contact'), ('cta', 'Call to action')], default='text', max_length=50),
        ),
        migrations.DeleteModel(
            name='HeaderMenu',
        ),
        migrations.DeleteModel(
            name='HeaderMenuItem',
        ),
    ]
