# Generated by Django 4.2.21 on 2026-08-27 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('category', models.CharField(choices=[('seo', 'SEO'), ('aeo', 'AEO'), ('geo', 'GEO'), ('llmo', 'LLMO'), ('eeat', 'E-E-A-T')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_search_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_ai_search_dashboard', 'Can view AI Search Dashboard'), ('start_scan', 'Can start scan'), ('manage_recommendations', 'Can manage recommendations')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('aeo_score', models.IntegerField(blank=True, null=True)),
                ('geo_score', models.IntegerField(blank=True, null=True)),
                ('llmo_score', models.IntegerField(blank=True, null=True)),
                ('eeat_score', models.IntegerField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='ai_search.website')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai_search.analysisissue')),
            ],
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('robots_meta', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('h1_headings', models.JSONField(default=list)),
                ('h2_headings', models.JSONField(default=list)),
                ('h3_headings', models.JSONField(default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('images_count', models.IntegerField(default=0)),
                ('images_with_alt', models.IntegerField(default=0)),
                ('internal_links_count', models.IntegerField(default=0)),
                ('external_links_count', models.IntegerField(default=0)),
                ('has_structured_data', models.BooleanField(default=False)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ai_search.websitescan')),
            ],
        ),
        migrations.AddField(
            model_name='analysisissue',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='ai_search.crawledpage'),
        ),
        migrations.AddField(
            model_name='analysisissue',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ai_search.websitescan'),
        ),
    ]
