# Generated by Django 4.2.21 on 2026-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='max_crawl_pages',
            field=models.IntegerField(default=10, help_text='Maximum number of pages to crawl per scan'),
        ),
    ]
