# Generated by Django 4.2.21 on 2026-08-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Payment Plan Template',
                'verbose_name_plural': 'Payment Plan Templates',
            },
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Project Code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Project Name', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Project Category', max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('detailed_description', models.TextField(blank=True)),
                ('default_estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_tax_configuration', models.CharField(blank=True, max_length=100)),
                ('validity_info', models.CharField(blank=True, help_text='Project Validity / Delivery Information', max_length=200)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.paymentplantemplate')),
            ],
            options={
                'verbose_name': 'Project Master',
                'verbose_name_plural': 'Project Masters',
            },
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Master',
                'verbose_name_plural': 'Service Masters',
            },
        ),
        migrations.CreateModel(
            name='ProjectMasterFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(blank=True, max_length=200)),
                ('feature_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=20)),
                ('optional', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='masters.projectmaster')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_links', to='masters.servicemaster')),
            ],
            options={
                'verbose_name': 'Project Master Feature',
                'verbose_name_plural': 'Project Master Features',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_percentage', models.BooleanField(default=False)),
                ('due_days', models.PositiveIntegerField(help_text='Number of days from quotation creation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='masters.paymentplantemplate')),
            ],
            options={
                'verbose_name': 'Payment Plan Milestone',
                'verbose_name_plural': 'Payment Plan Milestones',
                'ordering': ['id'],
            },
        ),
    ]
