# Generated by Django 4.2.21 on 2026-08-27 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_add_user_is_new_employee'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Probation End Date'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='probation_status',
            field=models.CharField(choices=[('none', 'None'), ('on_probation', 'On Probation'), ('confirmed', 'Confirmed'), ('extended', 'Extended')], default='none', max_length=20, verbose_name='Probation Status'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Probation End Date'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='probation_status',
            field=models.CharField(choices=[('none', 'None'), ('on_probation', 'On Probation'), ('confirmed', 'Confirmed'), ('extended', 'Extended')], default='none', max_length=20, verbose_name='Probation Status'),
        ),
        migrations.CreateModel(
            name='JoiningLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField(help_text='Supports placeholders: {employee_name}, {joining_date}, {designation}, {department}, {salary}, {company_name}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedJoiningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_joining_letters', to='employee.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_joining_letters_issued', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.joininglettertemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
