# Generated by Django 4.2.21 on 2026-08-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeworkinformation_probation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedjoiningletter',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
