# Generated by Django 4.2.21 on 2026-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Use home for the root page.', max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('html_content', models.TextField(help_text='Complete editable HTML for this page.')),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_navigation', models.BooleanField(default=True)),
                ('navigation_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('navigation_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='CyberWorldForge Tech', max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='website/branding/')),
                ('favicon', models.ImageField(blank=True, upload_to='website/branding/')),
                ('phone', models.CharField(default='+91 8819981884', max_length=40)),
                ('email', models.EmailField(default='chcyberarmy@gmail.com', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('default_meta_description', models.TextField(blank=True)),
                ('default_meta_keywords', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'My company setting',
                'verbose_name_plural': 'My company settings',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('contact', 'Contact'), ('career', 'Career'), ('newsletter', 'Newsletter')], default='contact', max_length=20)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
