from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("website", "0002_import_web_pages")]
    operations = [
        migrations.CreateModel(name="WebsiteService", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("slug", models.SlugField(unique=True)), ("short_description", models.TextField(blank=True)), ("full_description", models.TextField(blank=True)), ("icon", models.CharField(blank=True, max_length=100)), ("image", models.ImageField(blank=True, upload_to="website/services/")), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0))], options={"ordering": ("sort_order", "name")}),
        migrations.CreateModel(name="PricingPlan", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("price", models.DecimalField(decimal_places=2, max_digits=12)), ("billing_period", models.CharField(default="month", max_length=50)), ("description", models.TextField(blank=True)), ("features", models.TextField(blank=True, help_text="Enter one feature per line.")), ("button_text", models.CharField(default="Get Started", max_length=80)), ("button_url", models.CharField(default="/contact/", max_length=500)), ("is_featured", models.BooleanField(default=False)), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0))], options={"ordering": ("sort_order", "name")}),
        migrations.CreateModel(name="JobOpening", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=180)), ("slug", models.SlugField(unique=True)), ("location", models.CharField(blank=True, max_length=150)), ("job_type", models.CharField(blank=True, max_length=80)), ("experience", models.CharField(blank=True, max_length=100)), ("description", models.TextField(blank=True)), ("requirements", models.TextField(blank=True)), ("application_url", models.URLField(blank=True)), ("application_email", models.EmailField(blank=True, max_length=254)), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0))], options={"ordering": ("sort_order", "title")}),
        migrations.CreateModel(name="TeamMember", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("designation", models.CharField(blank=True, max_length=150)), ("bio", models.TextField(blank=True)), ("image", models.ImageField(blank=True, upload_to="website/team/")), ("linkedin_url", models.URLField(blank=True)), ("twitter_url", models.URLField(blank=True)), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0))], options={"ordering": ("sort_order", "name")}),
        migrations.CreateModel(name="WebsiteSection", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("section_type", models.CharField(default="content", max_length=50)), ("heading", models.CharField(max_length=200)), ("subheading", models.CharField(blank=True, max_length=255)), ("content", models.TextField(blank=True)), ("image", models.ImageField(blank=True, upload_to="website/sections/")), ("items", models.JSONField(blank=True, default=list, help_text='Optional list such as [{"title":"...","description":"..."}].')), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0)), ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="website.websitepage"))], options={"ordering": ("sort_order", "id")}),
    ]
