# Generated by Django 4.2.21 on 2026-08-01 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_initial'),
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetings',
            options={'permissions': (('join_meeting_call', 'Can join meeting calls'), ('start_meeting_call', 'Can start meeting calls'), ('record_meeting_call', 'Can record meeting calls'), ('manage_meeting_integrations', 'Can manage meeting integrations')), 'verbose_name': 'Meetings', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AddField(
            model_name='meetings',
            name='allow_captions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='allow_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='allow_recording',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meeting_type',
            field=models.CharField(choices=[('internal', 'Internal call'), ('external', 'External call')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='meetings',
            name='provider',
            field=models.CharField(choices=[('internal', 'Geeta Forgetech'), ('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('custom', 'Custom')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='meetings',
            name='room_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='meetings',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='MeetingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='pms.meetings')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_meeting_signals', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_meeting_signals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting_recordings/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='pms.meetings')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_messages', to='pms.meetings')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('language', models.CharField(default='en-IN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='pms.meetings')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('custom', 'Custom')], max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('tenant_id', models.CharField(blank=True, max_length=255)),
                ('api_base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_provider_configs', to='base.company')),
            ],
            options={
                'unique_together': {('company_id', 'provider')},
            },
        ),
    ]
