# Generated by Django 4.2.21 on 2026-08-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_meetings_options_meetings_allow_captions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingproviderconfig',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
