# Generated by Django 4.2.21 on 2026-08-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0004_meetingnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150)),
                ('api_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('api_secret', models.CharField(max_length=128)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('p2p_monthly', 'Peer-to-Peer Monthly'), ('pro_monthly', 'Pro Monthly'), ('enterprise_annual', 'Enterprise Annual'), ('custom', 'Custom')], default='free', max_length=20)),
                ('price_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('per_seat_price_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle_days', models.PositiveIntegerField(default=30)),
                ('max_participants', models.PositiveIntegerField(default=2)),
                ('max_duration_minutes', models.PositiveIntegerField(default=40)),
                ('allow_cloud_recording', models.BooleanField(default=False)),
                ('allow_screen_share', models.BooleanField(default=True)),
                ('allow_captions', models.BooleanField(default=True)),
                ('allow_developer_api', models.BooleanField(default=False)),
                ('max_api_calls_per_day', models.PositiveIntegerField(default=100)),
                ('max_concurrent_rooms', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('price_inr', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=255)),
                ('phonepe_merchant_id', models.CharField(blank=True, max_length=255)),
                ('phonepe_salt_key', models.CharField(blank=True, max_length=255)),
                ('phonepe_salt_index', models.CharField(blank=True, default='1', max_length=10)),
                ('phonepe_env', models.CharField(choices=[('UAT', 'UAT / Sandbox'), ('PROD', 'Production')], default='UAT', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=20)),
                ('peer_seats', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Payment'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('phonepe', 'PhonePe'), ('free', 'Free / Trial'), ('manual', 'Manual / Offline')], default='free', max_length=20)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='pms.meetingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('phonepe', 'PhonePe')], max_length=20)),
                ('order_id', models.CharField(db_index=True, max_length=255)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.meetingplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pms.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingGuestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_role', models.CharField(choices=[('host', 'Host'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_guest_tokens', to='pms.developerapikey')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_tokens', to='pms.meetings')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='pms.usersubscription'),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_api_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
