# Generated by Django 4.2.21 on 2026-08-27 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0005_developerapikey_meetingplan_paymentgatewayconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle_days', models.PositiveIntegerField(default=30)),
                ('max_participants', models.PositiveIntegerField(default=2)),
                ('max_duration_minutes', models.PositiveIntegerField(default=40)),
                ('allow_cloud_recording', models.BooleanField(default=False)),
                ('allow_screen_share', models.BooleanField(default=True)),
                ('allow_captions', models.BooleanField(default=True)),
                ('allow_developer_api', models.BooleanField(default=False)),
                ('max_api_calls_per_day', models.PositiveIntegerField(default=100)),
                ('max_concurrent_rooms', models.PositiveIntegerField(default=1)),
                ('storage_limit_mb', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('price_inr', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='meetingsignal',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='answer_employees',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='meetings',
            name='answerable_employees',
            field=models.ManyToManyField(blank=True, help_text='Select the employees who can respond to question template in this meeting, if any are added.', related_name='answerable_meetings', to='employee.employee', verbose_name='Answerable Employees'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='api_calls_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='api_calls_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='rooms_created_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='rooms_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='storage_used_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetingsignal',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingsignal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingsignal',
            name='signal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('waiting_room', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_invitations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='pms.meetings')),
            ],
            options={
                'verbose_name': 'Meeting Invitation',
                'verbose_name_plural': 'Meeting Invitations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EntitlementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('feature_check', 'Feature Check'), ('quota_consume', 'Quota Consume')], max_length=20)),
                ('feature_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quota_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_logs', to='pms.usersubscription')),
            ],
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='pms.organization'),
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(choices=[('developer_api', 'Developer API'), ('cloud_recording', 'Cloud Recording'), ('screen_share', 'Screen Share'), ('captions', 'Captions')], max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='pms.subscriptionplan')),
            ],
            options={
                'ordering': ('plan', 'feature_name'),
                'unique_together': {('plan', 'feature_name')},
            },
        ),
    ]
