# Generated by Django 4.2.21 on 2026-08-27 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0006_organization_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingsignal',
            options={},
        ),
        migrations.AddField(
            model_name='meetingplan',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetings',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='pms.organization'),
        ),
        migrations.AlterField(
            model_name='meetingsignal',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_meeting_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingsignal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_meeting_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingsignal',
            name='signal_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pms.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at',),
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
