# Generated by Django 4.2.21 on 2026-08-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('pms', '0007_alter_meetingsignal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='answer_employees',
            field=models.ManyToManyField(blank=True, help_text="Select the employees who can respond to question template in this meeting's, if any are added.", related_name='meeting_answer_employees', to='employee.employee', verbose_name='Answerable Employees legacy'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='employee_id',
            field=models.ManyToManyField(related_name='meeting_employee', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='manager',
            field=models.ManyToManyField(related_name='meeting_manager', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='pms.meetingplan'),
        ),
    ]
