# Generated by Django 4.2.21 on 2026-08-27 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_issuedjoiningletter_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequirement',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, related_name='requirement_assignments', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='requirements/attachments/'),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='modules_requested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_requirements', to='project.project'),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='revision_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='crmclient',
            name='is_portal_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crmclient',
            name='portal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RequirementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('modules_requested', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='requirements/revisions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='crm.clientrequirement')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.clientrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='CRMClientAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='crm.crmclient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_access_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
