# Generated by Django 4.2.21 on 2026-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company_crmclient_position_deal_crmtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('follow_up', 'Follow-up'), ('quotation_ready', 'Quotation Ready'), ('closed', 'Closed'), ('archived', 'Archived'), ('requirement_discovery', 'Requirement Discovery'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('confirmed_client', 'Confirmed Client'), ('active_project', 'Active Project'), ('payment', 'Payment'), ('project_delivery', 'Project Delivery'), ('successful_completion', 'Successful Completion'), ('long_term_client', 'Long-Term Client')], default='new', max_length=50),
        ),
    ]
