# Generated by Django 4.2.21 on 2026-08-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_modules', models.JSONField(default=dict, help_text='Modules/Features delivered')),
                ('delivery_status', models.CharField(default='pending', help_text='Delivery verification status', max_length=50)),
                ('payment_status', models.CharField(default='pending', help_text='Payment verification status', max_length=50)),
                ('approval_status', models.CharField(default='pending', help_text='Internal approvals status', max_length=50)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='project.project')),
            ],
            options={
                'verbose_name': 'Project Closure',
                'verbose_name_plural': 'Project Closures',
            },
        ),
        migrations.CreateModel(
            name='ProjectCommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Channel used (email, slack, etc.)', max_length=50)),
                ('summary_hash', models.CharField(help_text='Hash of the message content to dedupe', max_length=64)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', help_text='Send status', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='project.project')),
            ],
            options={
                'verbose_name': 'Project Communication Log',
                'verbose_name_plural': 'Project Communication Logs',
                'unique_together': {('project', 'channel', 'summary_hash')},
            },
        ),
    ]
